In [1]:
import pandas as pd
import os
import re
import numpy as np
from datetime import datetime, timedelta
import time
import pickle

In [61]:
os.chdir('C:\\DynamicData')

product = pd.read_csv('product.csv', encoding='utf-8')
session = pd.read_csv('Session.csv', encoding='utf-8')

C:\Users\anaconda\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

### product 전처리

In [5]:
product['PD_BUY_AM'] = list(map(lambda x:re.sub("\,", "",x), product['PD_BUY_AM']))
product['PD_BUY_AM'] = product['PD_BUY_AM'].astype('int64')

In [7]:
product['PD_BUY_CT'] = product['PD_BUY_CT'].astype('str')
product['PD_BUY_CT'] = list(map(lambda x:re.sub("\,", "",x), product['PD_BUY_CT']))
product['PD_BUY_CT'] = product['PD_BUY_CT'].astype('int64')

### session 데이터

### Session에 휴일여부 추가하기

In [3]:
session['Timestamp'] = 0

In [4]:
session['SESS_DT'] = session['SESS_DT'].astype('str')
session['SESS_DT'] = list(map(lambda x:datetime.strptime(x,'%Y%m%d'), session['SESS_DT']))
session['Timestamp'] = list(map(lambda x:datetime.timestamp(x), session['SESS_DT']))

In [5]:
Sat = pd.date_range(min(session.SESS_DT), max(session.SESS_DT), freq='W-SAT') #Saturday
Sun = pd.date_range(min(session.SESS_DT), max(session.SESS_DT), freq='W-SUN') #Sunday

In [6]:
Sat_Timestamp=list(map(lambda x:datetime.timestamp(x), Sat))
Sun_Timestamp=list(map(lambda x:datetime.timestamp(x), Sun))

In [7]:
Holiday = np.array(['20180505', '20180522', '20180606', '20180815', '20180923', '20180924', '20180925', ])
repic_Holiday = np.array(['20180507', '20180613', '20180926']) #5월7일, 9월26일: 대체 공휴일,6월 13일: 지방선거일
Holiday = np.append(Holiday, repic_Holiday)
Holiday = list(map(lambda x:datetime.strptime(x,'%Y%m%d'), Holiday))

In [8]:
Holiday_Timestamp=list(map(lambda x:datetime.timestamp(x), Holiday))

In [9]:
All_Timestamp = Sat_Timestamp + Sun_Timestamp + Holiday_Timestamp

In [10]:
session['Rest'] = 0 #휴일인 날

In [11]:
session.ix[session['Timestamp'].isin(All_Timestamp),'Rest']=1

C:\Users\anaconda\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

In [21]:
weekend_Timestamp = Sat_Timestamp + Sun_Timestamp
weekend_Timestamp = list(map(lambda x:datetime.fromtimestamp(x), weekend_Timestamp))

session['five_before'] = 0
session.ix[session['SESS_DT'].isin(list(map(lambda x: x+timedelta(days=-5), weekend_Timestamp))), 'five_before'] = 1

C:\Users\anaconda\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """

In [22]:
session

,CLNT_ID,SESS_ID,SESS_SEQ,SESS_DT,TOT_PAG_VIEW_CT,TOT_SESS_HR_V,DVC_CTG_NM,ZON_NM,CITY_NM,Timestamp,Rest,five_before
0,5873599,8641867,9,2018-05-09,82.0,"1,890",mobile,Daejeon,Daejeon,1.525792e+09,0,0
1,5873599,6616320,21,2018-06-11,105.0,"1,604",mobile,Busan,Busan,1.528643e+09,0,1
2,5873599,5886172,40,2018-06-24,41.0,632,mobile,Daejeon,Daejeon,1.529766e+09,1,0
3,5873884,1050889,15,2018-09-13,160.0,"1,035",mobile,Gyeonggi-do,Anyang,1.536764e+09,0,0
4,5874461,10298270,5,2018-04-12,13.0,298,mobile,Seoul,Seoul,1.523459e+09,0,0
5,5874701,608577,65,2018-09-20,41.0,444,mobile,Seoul,Seoul,1.537369e+09,0,0
6,5874829,1666766,87,2018-09-03,36.0,340,mobile,Seoul,Seoul,1.535900e+09,0,1
7,5874829,1670494,86,2018-09-03,103.0,976,mobile,Seoul,Seoul,1.535900e+09,0,1
8,5874829,1694242,85,2018-09-02,154.0,"3,099",mobile,Seoul,Seoul,1.535814e+09,1,0
9,5874829,1559438,92,2018-09-04,24.0,317,mobile,Seoul,Seoul,1.535987e+09,0,1
10,5874900,10229983,7,2018-04-13,207.0,"4,143",mobile,Seoul,Seoul,1.523545e+09,0,0
11,5874907,10855,2,2018-09-30,4.0,263,desktop,Gyeongsangbuk-do,Gumi-si,1.538233e+09,1,0
12,5876333,348698,16,2018-09-25,159.0,786,mobile,Seoul,Seoul,1.537801e+09,1,1
13,5876333,456326,15,2018-09-23,160.0,"1,038",mobile,Jeollabuk-do,Buan-gun,1.537628e+09,1,0
14,5876333,584142,13,2018-09-20,33.0,312,mobile,Seoul,Seoul,1.537369e+09,0,0
15,5876382,2141725,17,2018-08-25,72.0,"1,104",mobile,Seoul,Seoul,1.535123e+09,1,0
16,5876382,4493736,5,2018-07-16,42.0,666,mobile,Seoul,Seoul,1.531667e+09,0,1
17,5876601,6940393,47,2018-06-06,38.0,288,mobile,Seoul,Seoul,1.528211e+09,1,0
18,5876630,1511171,156,2018-09-05,104.0,689,mobile,Seoul,Seoul,1.536073e+09,0,0
19,5876630,223471,165,2018-09-27,77.0,861,mobile,Seoul,Seoul,1.537974e+09,0,0
20,5876800,8513782,366,2018-05-11,53.0,"1,022",mobile,Chungcheongbuk-do,Cheongju-si,1.525964e+09,0,0
21,5876800,7153099,429,2018-06-03,174.0,"2,019",mobile,Seoul,Seoul,1.527952e+09,1,0
22,5876800,7904215,397,2018-05-21,188.0,860,mobile,Chungcheongbuk-do,Cheongju-si,1.526828e+09,0,1
23,5876800,3836347,491,2018-07-27,122.0,459,mobile,Seoul,Seoul,1.532617e+09,0,0
24,5876800,3627244,500,2018-07-31,95.0,673,mobile,Seoul,Seoul,1.532963e+09,0,1
25,5876800,6785647,437,2018-06-09,61.0,159,mobile,Chungcheongbuk-do,Cheongju-si,1.528470e+09,1,0
26,5876800,8603946,362,2018-05-10,128.0,949,mobile,Chungcheongbuk-do,Cheongju-si,1.525878e+09,0,0
27,5876800,3197247,517,2018-08-07,157.0,"1,216",mobile,Seoul,Seoul,1.533568e+09,0,1
28,5876800,2310513,533,2018-08-22,108.0,888,mobile,Seoul,Seoul,1.534864e+09,0,0
29,5876912,447981,36,2018-09-23,23.0,756,mobile,Seoul,Seoul,1.537628e+09,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2712877,3555832,9296481,298,2018-04-28,338.0,"3,803",mobile,Seoul,Seoul,1.524841e+09,1,0
2712878,3552243,857890,70,2018-09-16,55.0,541,mobile,Incheon,Incheon,1.537024e+09,1,0
2712879,3553256,8128228,13,2018-05-18,39.0,341,mobile,Seoul,Seoul,1.526569e+09,0,0
2712880,3559213,8566684,167,2018-05-10,107.0,"1,014",mobile,Incheon,Incheon,1.525878e+09,0,0
2712881,3557770,5692621,377,2018-06-27,60.0,"2,236",mobile,Gangwon-do,Wonju-si,1.530025e+09,0,0
2712882,3557770,6833734,364,2018-06-08,104.0,"1,960",mobile,Gangwon-do,Wonju-si,1.528384e+09,0,0
2712883,3558515,8027926,199,2018-05-19,18.0,488,mobile,Busan,Busan,1.526656e+09,1,0
2712884,3561571,8410485,363,2018-05-13,123.0,"3,436",mobile,Gyeongsangnam-do,Gimhae-si,1.526137e+09,1,0
2712885,3569154,8031581,103,2018-05-19,152.0,"1,291",mobile,Jeollabuk-do,Jeonju-si,1.526656e+09,1,0
2712886,3566040,7612581,103,2018-05-26,56.0,705,mobile,Gyeongsangnam-do,Gimhae-si,1.527260e+09,1,0
2712887,3566629,6375372,95,2018-06-15,48.0,273,mobile,Seoul,Seoul,1.528988e+09,0,0
2712888,3568487,7191536,346,2018-06-02,41.0,441,mobile,Busan,Busan,1.527865e+09,1,0
2712889,3570334,5602994,2,2018-06-28,112.0,"2,611",mobile,Gyeongsangbuk-do,Andong,1.530112e+09,0,0
2712890,3642165,2189979,3,2018-08-24,29.0,"1,004",desktop,Gyeonggi-do,Ansan-si,1.535036e+09,0,0
2712891,3642354,4493999,83,2018-07-16,66.0,"1,719",mobile,Gwangju,Gwangju,1.531667e+09,0,1
2712892,3643587,10083218,12,2018-04-15,130.0,"6,203",desktop,Ulsan,Ulsan,1.523718e+09,1,0
2712893,3646640,6166681,16,2018-06-19,106.0,"2,177",mobile,Busan,Busan,1.529334e+09,0,1
2712894,3570720,4098757,500,2018-07-23,265.0,"2,246",mobile,Daegu,Daegu,1.532272e+09,0,1
2712895,3570720,3848780,515,2018-07-27,56.0,"1,039",mobile,Busan,Busan,1.532617e+09,0,0
2712896,3570720,5868666,454,2018-06-24,84.0,"1,589",mobile,Daegu,Daegu,1.529766e+09,1,0
2712897,3497799,8205641,1,2018-05-16,85.0,"1,828",desktop,Daejeon,Daejeon,1.526396e+09,0,0
2712898,3492307,2983998,25,2018-08-11,29.0,419,mobile,Gwangju,Gwangju,1.533913e+09,1,0
2712899,3499525,259993,2,2018-09-26,50.0,"2,477",desktop,Chungcheongbuk-do,Jecheon-si,1.537888e+09,1,0
2712900,3490918,1573185,16,2018-09-04,50.0,"1,546",mobile,Busan,Busan,1.535987e+09,0,1
2712901,3494680,9458833,488,2018-04-25,29.0,237,mobile,Gyeonggi-do,Gimpo-si,1.524582e+09,0,0
2712902,3500464,8713975,308,2018-05-08,71.0,423,mobile,Seoul,Seoul,1.525705e+09,0,1
2712903,3501155,4636571,86,2018-07-14,44.0,"2,090",desktop,Seoul,Seoul,1.531494e+09,1,0
2712904,3501397,582632,128,2018-09-20,164.0,"2,435",mobile,Seoul,Seoul,1.537369e+09,0,0
2712905,3573271,2328407,9,2018-08-22,5.0,986,desktop,Busan,Busan,1.534864e+09,0,0
2712906,3573758,8702345,17,2018-05-08,18.0,373,desktop,Chungcheongbuk-do,Cheongju-si,1.525705e+09,0,1

In [51]:
children_day = np.array(['2018-05-05'])
children_day = list(map(lambda x:datetime.strptime(x,'%Y-%m-%d'), children_day))
children_hotdays = []

children_hotdays.append(list(map(lambda x: x+timedelta(days=-3), children_day))[0])
children_hotdays.append(list(map(lambda x: x+timedelta(days=-4), children_day))[0])
children_hotdays.append(list(map(lambda x: x+timedelta(days=-5), children_day))[0])
children_hotdays.append(list(map(lambda x: x+timedelta(days=-6), children_day))[0])

session['children_hotday'] = 0
session.ix[session['SESS_DT'].isin(children_hotdays),'children_hotday'] = 1

C:\Users\anaconda\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  # This is added back by InteractiveShellApp.init_path()

In [52]:
teacher_day = np.array(['2018-05-15'])
teacher_day = list(map(lambda x:datetime.strptime(x,'%Y-%m-%d'), teacher_day))
teacher_hotdays = []

teacher_hotdays.append(list(map(lambda x: x+timedelta(days=-1), teacher_day))[0])

session['teacher_hotday'] = 0
session.ix[session['SESS_DT'].isin(teacher_hotdays), 'teacher_hotday'] = 1

C:\Users\anaconda\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [54]:
election_day = np.array(['2018-06-13']) 
election_day = list(map(lambda x:datetime.strptime(x,'%Y-%m-%d'), election_day))

election_hotdays = []

election_hotdays.append(list(map(lambda x: x+timedelta(days=-2), election_day))[0])
election_hotdays.append(list(map(lambda x: x+timedelta(days=-3), election_day))[0])

session['election_hotday'] = 0
session.ix[session['SESS_DT'].isin(election_hotdays), 'election_hotday'] = 1

C:\Users\anaconda\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  # Remove the CWD from sys.path while we load stuff.

In [60]:
with open('Preprosessing_Robin', 'wb') as wb:
    pickle.dump(session, wb)